local colors = require("sakurajima.colors")
local highlight = require("sakurajima.highlight")
local hop = require("sakurajima.plugins.hop")
local telescope = require("sakurajima.plugins.telescope")

local M = {}

function M.setup()
	highlight.setup("Normal", { fg = colors.dark_white, bg = colors.black })
	highlight.setup("Visual", { fg = colors.black, bg = colors.light_gray })
	highlight.setup("StatusLine", { fg = colors.dark_white, bg = colors.black })
	highlight.setup("StatusLineNC", { fg = colors.dark_white, bg = colors.black })
	highlight.setup("Cursor", { fg = colors.black, bg = colors.dark_white })
	highlight.setup("CursorLine", { bg = colors.winter_gray })
	highlight.setup("CursorLineNr", { fg = colors.dark_white, bg = colors.winter_gray, gui = colors.bold })
	highlight.setup("Search", { fg = colors.black, bg = colors.orange })
	highlight.setup("PmenuSel", { fg = colors.light_gray, bg = colors.winter_gray })
	highlight.setup("IncSearch", { fg = colors.black, bg = colors.yellow })
	highlight.setup("LineNr", { fg = colors.inactivegray, bg = colors.black })
	highlight.setup("NonText", { fg = colors.inactivegray })
	highlight.setup("Statement", { fg = colors.dark_cyan })
	highlight.setup("Comment", { fg = colors.dark_gray })
	highlight.setup("Constant", { fg = colors.dark_green })
	highlight.setup("Todo", { fg = colors.light_blue, bg = colors.black, sp = colors.dark_blue, gui = colors.undercurl })
	highlight.setup("Title", { fg = colors.dark_white, bg = colors.black })
	highlight.setup("Underlined", { gui = colors.underline })
	highlight.setup("Error", { fg = colors.dark_white, bg = colors.error })
	highlight.setup("Pmenu", { fg = colors.dark_white, bg = colors.cleared })
	highlight.setup("NormalFloat", { fg = colors.dark_white, bg = colors.cleared })
	highlight.setup("VertSplit", { fg = colors.black, bg = colors.cleared })
	highlight.setup("Function", { fg = colors.dark_yellow })
	highlight.setup("Type", { fg = colors.light_cyan })
	highlight.setup("SignColumn", { bg = colors.black, gui = colors.none })
	highlight.setup("MoreMsg", { fg = colors.dark_cyan, bg = colors.black })
	highlight.setup("ErrorMsg", { fg = colors.dark_white, bg = colors.error })
	highlight.setup("WarningMsg", { fg = colors.warn })
	highlight.setup("Identifier", { fg = colors.dark_green })
	highlight.setup("NvimInternalError", { fg = colors.dark_white, bg = colors.error })
	highlight.setup("Directory", { fg = colors.green })
	highlight.setup("MatchParen", { fg = colors.black, bg = colors.cyan })
	highlight.setup("DiffText", { fg = colors.dark_white, bg = colors.black })
	highlight.setup("DiffAdd", { fg = colors.green, bg = colors.black })
	highlight.setup("DiffDelete", { fg = colors.dark_red, bg = colors.black })
	highlight.setup("DiffChange", { fg = colors.yellow, bg = colors.black })
	highlight.setup("SpecialKey", { fg = colors.dark_red })
	highlight.setup("Special", { fg = colors.dark_yellow_green })
	highlight.setup("String", { fg = colors.dark_orange })
	highlight.setup("Question", { fg = colors.dark_green })
	highlight.setup("Boolean", { fg = colors.cyan })
	highlight.setup("@valiable", { fg = colors.dark_white })
	highlight.setup("QuickFixLine", { fg = colors.dark_cyan })
	highlight.setup("Added", { fg = colors.green })
	highlight.setup("Changed", { fg = colors.yellow })
	highlight.setup("Removed", { fg = colors.dark_red })

	vim.cmd("highlight link TabLine Function")
	vim.cmd("highlight link Boolean Constant")
	vim.cmd("highlight link Character Constant")
	vim.cmd("highlight link Conditional Statement")
	vim.cmd("highlight link CursorColumn CursorLine")
	vim.cmd("highlight link Define Statement")
	vim.cmd("highlight link Delimiter Comment")
	vim.cmd("highlight link Delimiter Statement")
	vim.cmd("highlight link Exception Statement")
	vim.cmd("highlight link Float Constant")
	vim.cmd("highlight link Folded Pmenu")
	vim.cmd("highlight link Include Statement")
	vim.cmd("highlight link Label Statement")
	vim.cmd("highlight link Macro Statement")
	vim.cmd("highlight link Number Constant")
	vim.cmd("highlight link Operator Statement")
	vim.cmd("highlight link PreCondit Statement")
	vim.cmd("highlight link PreProc Statement")
	vim.cmd("highlight link Repeat Statement")
	vim.cmd("highlight link Special Comment")
	vim.cmd("highlight link Special Statement")
	vim.cmd("highlight link SpecialChar Comment")
	vim.cmd("highlight link SpecialChar Statement")
	vim.cmd("highlight link SpecialComment Comment")
	vim.cmd("highlight link StorageClass Statement")
	vim.cmd("highlight link String Constant")
	vim.cmd("highlight link Structure Statement")
	vim.cmd("highlight link Tag Comment")
	vim.cmd("highlight link Tag Statement")
	vim.cmd("highlight link Typedef Statement")
	vim.cmd("highlight link WildMenu StatusLine")
	vim.cmd("highlight link Title Comment")

	highlight.setup("DiagnosticError", { fg = colors.error })
	vim.cmd("highlight link DiagnosticVirtualTextError DiagnosticError")
	vim.cmd("highlight link DiagnosticFloatingError DiagnosticError")
	vim.cmd("highlight link DiagnosticSignError DiagnosticError")

	highlight.setup("DiagnosticWarn", { fg = colors.warn })
	vim.cmd("highlight link DiagnosticVirtualTextWarn DiagnosticWarn")
	vim.cmd("highlight link DiagnosticFloatingWarn DiagnosticWarn")
	vim.cmd("highlight link DiagnosticSignWarn DiagnosticWarn")

	highlight.setup("DiagnosticInfo", { fg = colors.info })
	vim.cmd("highlight link DiagnosticVirtualTextInfo DiagnosticInfo")
	vim.cmd("highlight link DiagnosticFloatingInfo DiagnosticInfo")
	vim.cmd("highlight link DiagnosticSignInfo DiagnosticInfo")

	highlight.setup("DiagnosticHint", { fg = colors.hint })
	vim.cmd("highlight link DiagnosticVirtualTextHint DiagnosticHint")
	vim.cmd("highlight link DiagnosticFloatingHint DiagnosticHint")
	vim.cmd("highlight link DiagnosticSignHint DiagnosticHint")

	hop.setup()
	telescope.setup()

end

return M
